---
# tasks file for ansible-role-pam

- name: manage pam.d system-auth
  template: src=system-auth.j2 dest=/etc/pam.d/system-auth
            owner=root group=root mode=644

- name: manage pam.d system-auth-ac
  template: src=system-auth.j2 dest=/etc/pam.d/system-auth-ac
            owner=root group=root mode=644

- name: manage pam.d password-auth
  template: src=system-auth.j2 dest=/etc/pam.d/password-auth
            owner=root group=root mode=644
